### ISSUE TITLE
c# için kullanım

### ISSUE THREAD

**Issue by batu-han3428** [cancaliskan/canli-doviz-kuru#3]
Merhaba. Apinizi windows formda kullanmaya çalışıyorum ama deserialize ederken hata alıyorum. Aynı deserialize olayı başka apide çalışıyor ama. Apinizi c# dan çektiğimde nasıl deserialize edebilirim yardım edebilir misiniz?

**Comment by cancaliskan** [comment]
Merhabalar, json veri dönüyor uygun bir model oluşturup parse edebilirsin. Hata detayını paylaşırsan daha detaylı yardımcı olmaya çalışırım. 

Bu arada Herokuyu ücretsiz kullanıyorum, olası bir durumda api cevap dönmeyebilir bilginiz olsun

**Comment by batu-han3428** [comment]
altta ki gibi modeller yaptım:

```
public class DovizYeniDTO
    {
        public string ISOCode { get; set; }

        public decimal BuyingPrice { get; set; }

        public decimal SellingPrice { get; set; }

        public DateTimeOffset UpdateTime { get; set; }

    }

public class AsilDoviz
    {
        public DovizYeniDTO Dollar { get; set; }

        public DovizYeniDTO Euro { get; set; }

        public DovizYeniDTO GramGold { get; set; }
    }
```

şu şekilde verinizi alıyorum.:

```
            var client = new RestSharp.RestClient("https://cancaliskan-doviz-api.herokuapp.com/");
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);
```

buraya kadar sorun yok veriler geliyor. fakat deserialize ederken convert hatası veriyor. deserialize işlemim altta:

`
var veri = JsonSerializer.Deserialize<AsilDoviz>(response.Content);`

bunun dışında daha bir çok yol denedim ama yapamadım. windows formda deniyorum c#.  Eğer yardımcı olabilirseniz sevinirim. teşekkürler.

**Comment by batu-han3428** [comment]
Aşağıdaki string methodları kullanarak durumu çözdüm. o zaman deserialize yaptı.

```
var veri4 = response.Content.Replace("\\", "");
var asilVeri66 = veri4.Substring(1, veri4.Length - 2);
```

**Comment by cancaliskan** [comment]
Sorun çözülmüş diye anlıyorum, kolay gelsin
